function export_comsol_ddm_case(mphFile,partitionConfigFile,outputDir)
% Generic, non-destructive COMSOL MPH -> raw MPHTXT -> existing DDM input.
if ~isfile(mphFile),error('Input MPH does not exist: %s',mphFile),end;if ~isfolder(outputDir),mkdir(outputDir),end
cfg=load_ddm_partition_config(partitionConfigFile); addpath('D:\Program Files\COMSOL\COMSOL61\Multiphysics\mli');
import com.comsol.model.util.*
model=mphload(mphFile,['ddm_export_' regexprep(char(java.util.UUID.randomUUID),'-','')]); clean=onCleanup(@()ModelUtil.remove(model.tag));
info=inspect_comsol_heat_model(model,cfg); cfg=resolve_ddm_subdomains_from_selections(model,cfg,info); validatePartition(cfg,info); interfaces=detect_ddm_interfaces(info,cfg); paths=rawMeshPaths(outputDir,numel(cfg.subdomains)); if isfield(cfg,'reuse_existing_raw_mesh')&&cfg.reuse_existing_raw_mesh, if ~all(cellfun(@isfile,paths)),error('reuse_existing_raw_mesh requested but one or more raw MPHTXT files are missing.'),end, fprintf('Reusing existing COMSOL-native raw MPHTXT files after a prior interrupted validation.\n'); else, paths=build_ddm_subdomain_meshes(model,cfg,info,outputDir); end; meshes=cellfun(@parse_mphtxt_entities,paths,'UniformOutput',false); validation=validate_ddm_export(meshes,interfaces,info,cfg); input=generate_ddm_input(outputDir,cfg,info,meshes,interfaces,validation); writeArtifacts(outputDir,mphFile,partitionConfigFile,cfg,info,meshes,validation,input); fprintf('Generic DDM export complete: %s\n',input); clear clean
end
function paths=rawMeshPaths(out,n),paths=arrayfun(@(s)fullfile(out,'raw_mesh',sprintf('subdomain_%03d.mphtxt',s)),1:n,'UniformOutput',false);end
function validatePartition(cfg,info)
all=[];for s=1:numel(cfg.subdomains),all=[all,cfg.subdomains(s).domain_ids(:)'];end;if numel(unique(all))~=numel(all),error('A COMSOL Domain belongs to more than one subdomain.'),end;if ~isequal(sort(all),sort(info.heatDomains)),error('Partitioned Domain IDs must exactly cover Heat Transfer domains. configured=%s heat_domains=%s',mat2str(sort(all)),mat2str(sort(info.heatDomains))),end
end
function writeArtifacts(out,mph,cfgPath,cfg,info,meshes,v,input)
fid=fopen(fullfile(out,'comsol_entity_map.csv'),'w');fprintf(fid,'row_type,comsol_id,mphtxt_entity,adjacent_domains,subdomain,material_tag,k,rho,cp\n');for d=info.heatDomains,s=find(arrayfun(@(x)ismember(d,x.domain_ids),cfg.subdomains),1);m=info.materials(arrayfun(@(x)ismember(d,x.domains),info.materials));fprintf(fid,'domain,%d,%d,%d,%d,%s,%.17g,%.17g,%.17g\n',d,d,d,s,m.tag,m.k,m.rho,m.cp);end;for b=info.boundaries,ad=info.boundaryDomains{b};s=find(arrayfun(@(x)any(ismember(ad,x.domain_ids)),cfg.subdomains));fprintf(fid,'boundary,%d,%d,"%s","%s",,,,\n',b,b-1,join(ad),join(s));end;fclose(fid);
fid=fopen(fullfile(out,'interface_map.csv'),'w');fprintf(fid,'left_subdomain,right_subdomain,comsol_boundary_ids,mphtxt_tri_entity_ids,left_triangles,right_triangles,left_area,right_area,same_node_coordinates,same_triangulation\n');for q=1:numel(v.interfaces),x=v.interfaces(q);fprintf(fid,'%d,%d,"%s","%s",%d,%d,%.17g,%.17g,%d,%d\n',x.left,x.right,join(x.comsol),join(x.tri),x.A.triangles,x.B.triangles,x.A.area,x.B.area,x.sameNodes,x.sameTriangulation);end;fclose(fid);
fid=fopen(fullfile(out,'validation_report.txt'),'w');fprintf(fid,'Generic COMSOL DDM export: PASS\nSource MPH: %s\nCOMSOL version: %s\nMATLAB: %s\nGeometry length unit: %s\nCoordinate scale to SI: %.17g\nInput: %s\n',mph,info.comsolVersion,version,info.geometryLengthUnit,info.coordinateScale,input);for s=1:numel(meshes),fprintf(fid,'SD%d nodes=%d tets=%d boundary_triangles=%d SHA256=%s\n',s,size(meshes{s}.V,1),size(meshes{s}.tet,1),size(meshes{s}.tri,1),sha(meshes{s}.path));end;for q=1:numel(v.interfaces),x=v.interfaces(q);fprintf(fid,'Interface SD%d-SD%d COMSOL=%s tri=%s left=%d/%d/%.17g right=%d/%d/%.17g same_nodes=%d same_triangulation=%d\n',x.left,x.right,join(x.comsol),join(x.tri),x.A.triangles,x.A.nodes,x.A.area,x.B.triangles,x.B.nodes,x.B.area,x.sameNodes,x.sameTriangulation);end;fclose(fid);
manifest=struct('source_mph',mph,'partition_config',cfgPath,'partition_source',cfg.partition_source,'comsol_version',info.comsolVersion,'matlab_version',version,'geometry_length_unit',info.geometryLengthUnit,'coordinate_scale_to_si',info.coordinateScale,'subdomains',cfg.subdomains,'numbering_rules',struct('domain_tet_entity','identity (validated)','boundary_tri_entity','COMSOL Boundary ID - 1 (validated)'), 'ddm_input',input);fid=fopen(fullfile(out,'case_manifest.json'),'w');fprintf(fid,'%s',jsonencode(manifest));fclose(fid);
end
function s=join(x),s=strjoin(arrayfun(@num2str,x,'UniformOutput',false),';');end
function h=sha(p),md=java.security.MessageDigest.getInstance('SHA-256');md.update(uint8(fileread(p)));h=upper(reshape(dec2hex(mod(double(md.digest()),256),2).',1,[]));end
